// <auto-generated />
namespace ExchangeFreelancing.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class requsetadd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(requsetadd));
        
        string IMigrationMetadata.Id
        {
            get { return "201503071216556_requsetadd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
